# Generated by Django 6.0.6 on 2026-06-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_alter_post_id'),
        ('posting', '002_enable_pg_terms'),
    ]

    operations = [
    ]
